# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.IntegerField()),
                ('menuName', models.CharField(max_length=64)),
                ('shopId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('menuId', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('orderTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.IntegerField()),
                ('shopName', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
