# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0002_auto_20170724_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menuId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='select',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
