# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0003_auto_20170729_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='id',
        ),
        migrations.AddField(
            model_name='shop',
            name='shopId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(max_length=64, verbose_name='\u5546\u94fa'),
        ),
    ]
