# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0004_auto_20170731_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shopName',
            field=models.CharField(max_length=64, verbose_name='\u5546\u94fa\u540d'),
        ),
    ]
