# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0006_auto_20170808_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField(default=0, verbose_name='\u516c\u53f8ID')),
                ('companyName', models.CharField(max_length=128, verbose_name='\u516c\u53f8\u540d')),
            ],
            options={
                'verbose_name': '\u516c\u53f8',
                'verbose_name_plural': '\u516c\u53f8\u7ba1\u7406',
            },
        ),
    ]
